LANGUAGES = {
    "en": {
        "title": "YouTube Video and Audio Downloader",
        "title_twitter": "Twitter (X) Video Downloader",
        "title_facebook": "Facebook Video Downloader",
        "title_tiktok": "TikTok Video Downloader",
        "title_instagram": "Instagram Video & Reels Downloader",
        "title_soundcloud": "SoundCloud Audio Downloader",
        "title_reddit": "Reddit Video Downloader",
        "validate": "Validate",
        "download": "Download",
        "language": "Language Selection",
        "go_back": "Go Back",
        "url_label": "URL:",
        "folder_label": "Download Folder:",
        "format_label": "Format:",
        "format_label_audio": "Audio Format:",
        "format_label_video": "Video Format:",
        "list_type_video": "Video",
        "list_type_audio": "Audio",
        "quality_360p": "360p",
        "quality_480p": "480p",
        "quality_720p": "720p",
        "quality_1080p": "1080p",
        "quality_1440p": "1440p",
        "quality_2160p": "2160p (4K)",
        "quality_4320p": "4320p (8K)",
        "mp4": "MP4",
        "webm": "WEBM",
        "mkv": "MKV",
        "mp3": "MP3",
        "m4a": "M4A",
        "ogg": "OGG",
        "flac": "FLAC",
        "opus": "Opus",
        "wav": "WAV",
        "browse": "Browse",
        "theme": "Change Theme",
        "download_type": "Download Type:",
        "type_video": "Single Video",
        "type_playlist": "Playlist",
        "subtitle_download": "Download Subtitles",
        "subtitle_languages": "Subtitle Languages (e.g., en,tr):",
        "save_thumbnail": "Save Thumbnail",
        "ffmpeg_missing_title": "FFmpeg Missing",
        "ffmpeg_missing_text": "FFmpeg not found for audio/video merging and conversion.\n"
                             "Please install FFmpeg and add it to your system PATH.\n"
                             "The application may fail when downloading audio or high-quality video.",
        "thumbnail_save_success_title": "Success",
        "thumbnail_save_success_text": "Thumbnail saved to {path}",
        "youtube_invalid_url": "Invalid YouTube or YouTube Music URL!",
        "twitter_invalid_url": "Invalid Twitter (X) URL! Please enter a tweet link.",
        "facebook_invalid_url": "Invalid Facebook URL! Please enter a video or reel link.",
        "tiktok_invalid_url": "Invalid TikTok URL! Please enter a video link.",
        "instagram_invalid_url": "Invalid Instagram URL! Please enter a post or reel link.",
        "soundcloud_invalid_url": "Invalid SoundCloud URL! Please enter a track or playlist link.",
        "reddit_invalid_url": "Invalid Reddit URL! Please enter a post link.",
        "download_in_progress": "📥 Downloading in progress: {percent}% complete",
        "download_complete": "✅ Download completed successfully!",
        "download_error": "❌ An error occurred during download.",
        "download_starting": "⏳ Download starting... Please wait.",
        "download_speed_eta": "🚀 Speed: {speed} | ⏳ Time remaining: {eta}",
        "download_canceled": "⚠️ Download canceled.",
        "update_button": "Check for Updates",
        "update_checking": "Checking for updates...",
        "update_success": "yt-dlp is already up to date.",
        "update_available": "yt-dlp updated successfully!",
        "update_error": "An error occurred during the update:\n{error}",
        
        # --- Ayar Metinleri ---
        "settings_title": "Settings",
        "settings_tab_general": "General",
        "settings_tab_advanced": "Advanced",
        "settings_cookie_label": "Cookies File Path (.txt):",
        "settings_cookie_tooltip": "Select a cookies.txt file (for private videos or age-restricted content).",
        "settings_save_button": "Save",
        "settings_close_button": "Close",
        "settings_button": "Settings",
        "group_input": "Input",
        "group_options": "Download Options",
        "ffmpeg_warning_text": "FFmpeg not found. This is required for audio and high-quality video downloads.\n\nPlease install it using the 'Auto-Install FFmpeg' button in Settings -> Advanced.",
        "settings_group_cookie": "Cookie File",
        "settings_group_ffmpeg": "FFmpeg Installation",
        "ffmpeg_status_found": "Status: Found (AppData or PATH)",
        "ffmpeg_status_missing": "Status: Not Found",
        "ffmpeg_button_install": "Auto-Install",
        "ffmpeg_button_reinstall": "Re-Install / Update",
        "ffmpeg_tooltip_found": "FFmpeg is found on your system (in your AppData folder or system PATH).",
        "ffmpeg_tooltip_missing": "This will install FFmpeg to your user's AppData folder and add it to your PATH. No admin rights required.",
        "clipboard_monitor": "Auto-Paste from Clipboard"
    },
    "tr": {
        "title": "YouTube Video ve Ses İndirici",
        "title_twitter": "Twitter (X) Video İndirici",
        "title_facebook": "Facebook Video İndirici",
        "title_tiktok": "TikTok Video İndirici",
        "title_instagram": "Instagram Video & Reels İndirici",
        "title_soundcloud": "SoundCloud Müzik İndirici",
        "title_reddit": "Reddit Video İndirici",
        "validate": "Doğrula",
        "download": "İndir",
        "language": "Dil Seçimi",
        "go_back": "Geri Git",
        "url_label": "URL:",
        "folder_label": "İndirilen Klasör:",
        "format_label": "Format:",
        "format_label_audio": "Ses Formatı:",
        "format_label_video": "Video Formatı:",
        "list_type_video": "Video",
        "list_type_audio": "Ses",
        "quality_360p": "360p",
        "quality_480p": "480p",
        "quality_720p": "720p",
        "quality_1080p": "1080p",
        "quality_1440p": "1440p",
        "quality_2160p": "2160p (4K)",
        "quality_4320p": "4320p (8K)",
        "mp4": "MP4",
        "webm": "WEBM",
        "mkv": "MKV",
        "mp3": "MP3",
        "m4a": "M4A",
        "ogg": "OGG",
        "flac": "FLAC",
        "opus": "Opus",
        "wav": "WAV",
        "browse": "Gözat",
        "theme": "Temayı Değiştir",
        "download_type": "İndirme Türü:",
        "type_video": "Tek Video",
        "type_playlist": "Oynatma Listesi",
        "subtitle_download": "Altyazıları İndir",
        "subtitle_languages": "Altyazı Dilleri (örn: en,tr):",
        "save_thumbnail": "Kapak Resmini Kaydet",
        "ffmpeg_missing_title": "FFmpeg Eksik",
        "ffmpeg_missing_text": "Ses/Video birleştirme ve dönüştürme için FFmpeg bulunamadı.\n"
                             "Lütfen FFmpeg'i yükleyin ve sistem PATH'ine ekleyin.\n"
                             "Uygulama, ses veya yüksek kaliteli video indirirken hata verebilir.",
        "thumbnail_save_success_title": "Başarılı",
        "thumbnail_save_success_text": "Kapak resmi şuraya kaydedildi: {path}",
        "youtube_invalid_url": "Geçersiz YouTube veya YouTube Music URL'si!",
        "twitter_invalid_url": "Geçersiz Twitter (X) URL'si! Lütfen tweet linkini girin.",
        "facebook_invalid_url": "Geçersiz Facebook URL'si! Lütfen video veya reel linkini girin.",
        "tiktok_invalid_url": "Geçersiz TikTok URL'si! Lütfen video linkini girin.",
        "instagram_invalid_url": "Geçersiz Instagram URL'si! Lütfen post veya reel linkini girin.",
        "soundcloud_invalid_url": "Geçersiz SoundCloud URL'si! Lütfen bir parça veya çalma listesi linki girin.",
        "reddit_invalid_url": "Geçersiz Reddit URL'si! Lütfen bir gönderi linki girin.",
        "download_in_progress": "📥 İndirme devam ediyor: {percent}% tamamlandı",
        "download_complete": "✅ İndirme başarıyla tamamlandı!",
        "download_error": "❌ İndirme sırasında bir hata oluştu.",
        "download_starting": "⏳ İndirme başlatılıyor... Lütfen bekleyin.",
        "download_speed_eta": "🚀 Hız: {speed} | ⏳ Kalan süre: {eta}",
        "download_canceled": "⚠️ İndirme iptal edildi.",
        "update_button": "Güncellemeleri Denetle",
        "update_checking": "Güncellemeler denetleniyor...",
        "update_success": "yt-dlp zaten güncel.",
        "update_available": "yt-dlp başarıyla güncellendi!",
        "update_error": "Güncelleme sırasında bir hata oluştu:\n{error}",
        
        # --- Ayar Metinleri ---
        "settings_title": "Ayarlar",
        "settings_tab_general": "Genel",
        "settings_tab_advanced": "Gelişmiş",
        "settings_cookie_label": "Çerez Dosyası Yolu (.txt):",
        "settings_cookie_tooltip": "Özel veya yaş kısıtlamalı videolar için çerez dosyası (.txt) seçin.",
        "settings_save_button": "Kaydet",
        "settings_close_button": "Kapat",
        "settings_button": "Ayarlar",
        "group_input": "Giriş Bilgileri",
        "group_options": "İndirme Seçenekleri",
        "ffmpeg_warning_text": "FFmpeg bulunamadı. Bu, ses ve yüksek kaliteli videolar için gereklidir.\n\nLütfen Ayarlar -> Gelişmiş menüsünden 'Otomatik Kur' butonunu kullanarak kurun.",
        "settings_group_cookie": "Çerez Dosyası",
        "settings_group_ffmpeg": "FFmpeg Kurulumu",
        "ffmpeg_status_found": "Durum: Bulundu (AppData veya PATH)",
        "ffmpeg_status_missing": "Durum: Bulunamadı",
        "ffmpeg_button_install": "Otomatik Kur",
        "ffmpeg_button_reinstall": "Yeniden Kur / Güncelle",
        "ffmpeg_tooltip_found": "FFmpeg sisteminizde (AppData klasörünüzde veya sistem PATH) bulundu.",
        "ffmpeg_tooltip_missing": "FFmpeg'i AppData klasörünüze kurar ve sistem PATH'inize ekler. Yönetici izni gerekmez.",
        "clipboard_monitor": "Panoyu Otomatik İzle"
    },
    "es": {
        "title": "Descargador de Video y Audio de YouTube",
        "title_twitter": "Descargador de Video de Twitter (X)",
        "title_facebook": "Descargador de Video de Facebook",
        "title_tiktok": "Descargador de Video de TikTok",
        "title_instagram": "Descargador de Video y Reels de Instagram",
        "title_soundcloud": "Descargador de Audio de SoundCloud",
        "title_reddit": "Descargador de Video de Reddit",
        "validate": "Validar",
        "download": "Descargar",
        "language": "Selección de Idioma",
        "go_back": "Volver",
        "url_label": "URL:",
        "folder_label": "Carpeta de Descarga:",
        "format_label": "Formato:",
        "format_label_audio": "Formato de Audio:",
        "format_label_video": "Formato de Video:",
        "list_type_video": "Vídeo",
        "list_type_audio": "Audio",
        "quality_360p": "360p",
        "quality_480p": "480p",
        "quality_720p": "720p",
        "quality_1080p": "1080p",
        "quality_1440p": "1440p",
        "quality_2160p": "2160p (4K)",
        "quality_4320p": "4320p (8K)",
        "mp4": "MP4",
        "webm": "WEBM",
        "mkv": "MKV",
        "mp3": "MP3",
        "m4a": "M4A",
        "ogg": "OGG",
        "flac": "FLAC",
        "opus": "Opus",
        "wav": "WAV",
        "browse": "Buscar",
        "theme": "Cambiar Tema",
        "download_type": "Tipo de Descarga:",
        "type_video": "Video Único",
        "type_playlist": "Lista de Reproducción",
        "subtitle_download": "Descargar Subtítulos",
        "subtitle_languages": "Idiomas de Subtítulos (ej: en,es):",
        "save_thumbnail": "Guardar Miniatura",
        "ffmpeg_missing_title": "Falta FFmpeg",
        "ffmpeg_missing_text": "No se encontró FFmpeg para fusionar y convertir audio/video.\n"
                             "Instale FFmpeg y agréguelo a su PATH del sistema.\n"
                             "La aplicación puede fallar al descargar audio o video de alta calidad.",
        "thumbnail_save_success_title": "Éxito",
        "thumbnail_save_success_text": "Miniatura guardada en {path}",
        "youtube_invalid_url": "¡URL de YouTube o YouTube Music no válida!",
        "twitter_invalid_url": "¡URL de Twitter (X) no válida! Por favor, ingrese un enlace de tweet.",
        "facebook_invalid_url": "¡URL de Facebook no válida! Por favor, ingrese un enlace de video o reel.",
        "tiktok_invalid_url": "¡URL de TikTok no válida! Por favor, ingrese un enlace de video.",
        "instagram_invalid_url": "¡URL de Instagram no válida! Por favor, ingrese un enlace de publicación o reel.",
        "soundcloud_invalid_url": "¡URL de SoundCloud no válida! Por favor, ingrese un enlace de pista o lista de reproducción.",
        "reddit_invalid_url": "¡URL de Reddit no válida! Por favor, ingrese un enlace de publicación.",
        "download_in_progress": "📥 Descargando: {percent}% completado",
        "download_complete": "✅ ¡Descarga completada con éxito!",
        "download_error": "❌ Se produjo un error during la descarga.",
        "download_starting": "⏳ Iniciando la descarga... Por favor, espere.",
        "download_speed_eta": "🚀 Velocidad: {speed} | ⏳ Tiempo restante: {eta}",
        "download_canceled": "⚠️ Descarga cancelada.",
        "update_button": "Buscar Actualizaciones",
        "update_checking": "Buscando actualizaciones...",
        "update_success": "yt-dlp ya está actualizado.",
        "update_available": "¡yt-dlp actualizado con éxito!",
        "update_error": "Ocurrió un error during la actualización:\n{error}",
        
        # --- Ayar Metinleri ---
        "settings_title": "Ajustes",
        "settings_tab_general": "General",
        "settings_tab_advanced": "Avanzado",
        "settings_cookie_label": "Ruta del archivo de Cookies (.txt):",
        "settings_cookie_tooltip": "Seleccione un archivo cookies.txt (para videos privados o con restricción de edad).",
        "settings_save_button": "Guardar",
        "settings_close_button": "Cerrar",
        "settings_button": "Ajustes",
        "group_input": "Entrada",
        "group_options": "Opciones de Descarga",
        "ffmpeg_warning_text": "FFmpeg no encontrado. Es necesario para descargas de audio y video de alta calidad.\n\nPor favor, instálelo usando el botón 'Instalación Automática' en Ajustes -> Avanzado.",
        "settings_group_cookie": "Archivo de Cookies",
        "settings_group_ffmpeg": "Instalación de FFmpeg",
        "ffmpeg_status_found": "Estado: Encontrado (AppData o PATH)",
        "ffmpeg_status_missing": "Estado: No Encontrado",
        "ffmpeg_button_install": "Instalación Automática",
        "ffmpeg_button_reinstall": "Reinstalar / Actualizar",
        "ffmpeg_tooltip_found": "FFmpeg se encuentra en su sistema (en su carpeta AppData o PATH del sistema).",
        "ffmpeg_tooltip_missing": "Esto instalará FFmpeg en su carpeta AppData y lo agregará a su PATH. No se requieren derechos de administrador.",
        "clipboard_monitor": "Pegar autom. desde portapapeles"
    },
    "de": {
        "title": "YouTube Video und Audio Downloader",
        "title_twitter": "Twitter (X) Video Downloader",
        "title_facebook": "Facebook Video Downloader",
        "title_tiktok": "TikTok Video Downloader",
        "title_instagram": "Instagram Video & Reels Downloader",
        "title_soundcloud": "SoundCloud Audio-Downloader",
        "title_reddit": "Reddit Video-Downloader",
        "validate": "Validieren",
        "download": "Herunterladen",
        "language": "Sprache Auswahl",
        "go_back": "Zurück",
        "url_label": "URL:",
        "folder_label": "Download Ordner:",
        "format_label": "Format:",
        "format_label_audio": "Audio-Format:",
        "format_label_video": "Video-Format:",
        "list_type_video": "Video",
        "list_type_audio": "Audio",
        "quality_360p": "360p",
        "quality_480p": "480p",
        "quality_720p": "720p",
        "quality_1080p": "1080p",
        "quality_1440p": "1440p",
        "quality_2160p": "2160p (4K)",
        "quality_4320p": "4320p (8K)",
        "mp4": "MP4",
        "webm": "WEBM",
        "mkv": "MKV",
        "mp3": "MP3",
        "m4a": "M4A",
        "ogg": "OGG",
        "flac": "FLAC",
        "opus": "Opus",
        "wav": "WAV",
        "browse": "Durchsuchen",
        "theme": "Thema ändern",
        "download_type": "Download-Typ:",
        "type_video": "Einzelnes Video",
        "type_playlist": "Playlist",
        "subtitle_download": "Untertitel herunterladen",
        "subtitle_languages": "Untertitelsprachen (z.B. en,de):",
        "save_thumbnail": "Vorschaubild speichern",
        "ffmpeg_missing_title": "FFmpeg fehlt",
        "ffmpeg_missing_text": "FFmpeg zum Zusammenführen und Konvertieren von Audio/Video nicht gefunden.\n"
                             "Bitte installieren Sie FFmpeg und fügen Sie es Ihrem System-PATH hinzu.\n"
                             "Die Anwendung könnte beim Herunterladen von Audio oder hochwertigem Video fehlschlagen.",
        "thumbnail_save_success_title": "Erfolg",
        "thumbnail_save_success_text": "Vorschaubild gespeichert unter {path}",
        "youtube_invalid_url": "Ungültige YouTube- oder YouTube Music-URL!",
        "twitter_invalid_url": "Ungültige Twitter (X)-URL! Bitte geben Sie einen Tweet-Link ein.",
        "facebook_invalid_url": "Ungültige Facebook-URL! Bitte geben Sie einen Video- oder Reel-Link ein.",
        "tiktok_invalid_url": "Ungültige TikTok-URL! Bitte geben Sie einen Video-Link ein.",
        "instagram_invalid_url": "Ungültige Instagram-URL! Bitte geben Sie einen Post- oder Reel-Link ein.",
        "soundcloud_invalid_url": "Ungültige SoundCloud-URL! Bitte geben Sie einen Track- oder Playlist-Link ein.",
        "reddit_invalid_url": "Ungültige Reddit-URL! Bitte geben Sie einen Beitragslink ein.",
        "download_in_progress": "📥 Download läuft: {percent}% abgeschlossen",
        "download_complete": "✅ Download erfolgreich abgeschlossen!",
        "download_error": "❌ Beim Download ist ein Fehler aufgetreten.",
        "download_starting": "⏳ Download wird gestartet... Bitte warten.",
        "download_speed_eta": "🚀 Geschwindigkeit: {speed} | ⏳ Verbleibende Zeit: {eta}",
        "download_canceled": "⚠️ Download abgebrochen.",
        "update_button": "Nach Updates suchen",
        "update_checking": "Suche nach Updates...",
        "update_success": "yt-dlp ist bereits auf dem neuesten Stand.",
        "update_available": "yt-dlp erfolgreich aktualisiert!",
        "update_error": "Ein Fehler ist während des Updates aufgetreten:\n{error}",
        
        # --- Ayar Metinleri ---
        "settings_title": "Einstellungen",
        "settings_tab_general": "Allgemein",
        "settings_tab_advanced": "Erweitert",
        "settings_cookie_label": "Cookie-Dateipfad (.txt):",
        "settings_cookie_tooltip": "Wählen Sie eine cookies.txt-Datei (für private Videos oder Inhalte mit Altersbeschränkung).",
        "settings_save_button": "Speichern",
        "settings_close_button": "Schließen",
        "settings_button": "Einstellungen",
        "group_input": "Eingabe",
        "group_options": "Download-Optionen",
        "ffmpeg_warning_text": "FFmpeg nicht gefunden. Dies wird für Audio- und hochwertige Video-Downloads benötigt.\n\nBitte installieren Sie es über die Schaltfläche 'Automatische Installation' in Einstellungen -> Erweitert.",
        "settings_group_cookie": "Cookie-Datei",
        "settings_group_ffmpeg": "FFmpeg-Installation",
        "ffmpeg_status_found": "Status: Gefunden (AppData oder PATH)",
        "ffmpeg_status_missing": "Status: Nicht gefunden",
        "ffmpeg_button_install": "Automatische Installation",
        "ffmpeg_button_reinstall": "Neu installieren / Aktualisieren",
        "ffmpeg_tooltip_found": "FFmpeg wurde auf Ihrem System gefunden (in Ihrem AppData-Ordner oder System-PATH).",
        "ffmpeg_tooltip_missing": "Dies installiert FFmpeg in Ihrem AppData-Ordner und fügt es Ihrem PATH hinzu. Keine Admin-Rechte erforderlich.",
        "clipboard_monitor": "Automatisch aus Zwischenablage"
    },
    "fr": {
        "title": "Téléchargeur de vidéos et d'audio YouTube",
        "title_twitter": "Téléchargeur de vidéos Twitter (X)",
        "title_facebook": "Téléchargeur de vidéos Facebook",
        "title_tiktok": "Téléchargeur de vidéos TikTok",
        "title_instagram": "Téléchargeur de vidéos et reels Instagram",
        "title_soundcloud": "Téléchargeur Audio SoundCloud",
        "title_reddit": "Téléchargeur de vidéos Reddit",
        "validate": "Valider",
        "download": "Télécharger",
        "language": "Sélection de la langue",
        "go_back": "Retour",
        "url_label": "URL:",
        "folder_label": "Dossier de téléchargement:",
        "format_label": "Format:",
        "format_label_audio": "Format Audio:",
        "format_label_video": "Format Vidéo:",
        "list_type_video": "Vidéo",
        "list_type_audio": "Audio",
        "quality_360p": "360p",
        "quality_480p": "480p",
        "quality_720p": "720p",
        "quality_1080p": "1080p",
        "quality_1440p": "1440p",
        "quality_2160p": "2160p (4K)",
        "quality_4320p": "4320p (8K)",
        "mp4": "MP4",
        "webm": "WEBM",
        "mkv": "MKV",
        "mp3": "MP3",
        "m4a": "M4A",
        "ogg": "OGG",
        "flac": "FLAC",
        "opus": "Opus",
        "wav": "WAV",
        "browse": "Parcourir",
        "theme": "Changer de thème",
        "download_type": "Type de Téléchargement:",
        "type_video": "Vidéo Unique",
        "type_playlist": "Playlist",
        "subtitle_download": "Télécharger les sous-titres",
        "subtitle_languages": "Langues des sous-titres (ex: en,fr):",
        "save_thumbnail": "Enregistrer la miniature",
        "ffmpeg_missing_title": "FFmpeg manquant",
        "ffmpeg_missing_text": "FFmpeg introuvable pour la fusion et la conversion audio/vidéo.\n"
                             "Veuillez installer FFmpeg et l'ajouter à votre PATH système.\n"
                             "L'application risque d'échouer lors du téléchargement d'audio ou de vidéo de haute qualité.",
        "thumbnail_save_success_title": "Succès",
        "thumbnail_save_success_text": "Miniature enregistrée dans {path}",
        "youtube_invalid_url": "URL YouTube ou YouTube Music invalide !",
        "twitter_invalid_url": "URL Twitter (X) invalide ! Veuillez saisir un lien de tweet.",
        "facebook_invalid_url": "URL Facebook invalide ! Veuillez saisir un lien de vidéo ou de reel.",
        "tiktok_invalid_url": "URL TikTok invalide ! Veuillez saisir un lien vidéo.",
        "instagram_invalid_url": "URL Instagram invalide ! Veuillez saisir un lien de post ou de reel.",
        "soundcloud_invalid_url": "URL SoundCloud invalide ! Veuillez saisir un lien de piste ou de playlist.",
        "reddit_invalid_url": "URL Reddit invalide ! Veuillez saisir un lien de publication.",
        "download_in_progress": "📥 Téléchargement en cours : {percent}% terminé",
        "download_complete": "✅ Téléchargement terminé avec succès!",
        "download_error": "❌ Une erreur s'est produite lors du téléchargement.",
        "download_starting": "⏳ Démarrage du téléchargement... Veuillez patienter.",
        "download_speed_eta": "🚀 Vitesse: {speed} | ⏳ Temps restant: {eta}",
        "download_canceled": "⚠️ Téléchargement annulé.",
        "update_button": "Vérifier les mises à jour",
        "update_checking": "Vérification des mises à jour...",
        "update_success": "yt-dlp est déjà à jour.",
        "update_available": "yt-dlp mis à jour avec succès!",
        "update_error": "Une erreur s'est produite lors de la mise à jour:\n{error}",
        
        # --- Ayar Metinleri ---
        "settings_title": "Paramètres",
        "settings_tab_general": "Général",
        "settings_tab_advanced": "Avancé",
        "settings_cookie_label": "Chemin du fichier de cookies (.txt):",
        "settings_cookie_tooltip": "Sélectionnez un fichier cookies.txt (pour les vidéos privées ou à contenu restreint).",
        "settings_save_button": "Enregistrer",
        "settings_close_button": "Fermer",
        "settings_button": "Paramètres",
        "group_input": "Entrée",
        "group_options": "Options de téléchargement",
        "ffmpeg_warning_text": "FFmpeg introuvable. Requis pour les téléchargements audio et vidéo de haute qualité.\n\nVeuillez l'installer via le bouton 'Installation auto' dans Paramètres -> Avancé.",
        "settings_group_cookie": "Fichier de cookies",
        "settings_group_ffmpeg": "Installation de FFmpeg",
        "ffmpeg_status_found": "Statut: Trouvé (AppData ou PATH)",
        "ffmpeg_status_missing": "Statut: Introuvable",
        "ffmpeg_button_install": "Installation auto",
        "ffmpeg_button_reinstall": "Réinstaller / Mettre à jour",
        "ffmpeg_tooltip_found": "FFmpeg est trouvé sur votre système (dans votre dossier AppData ou PATH système).",
        "ffmpeg_tooltip_missing": "Ceci installera FFmpeg dans votre dossier AppData et l'ajoutera à votre PATH. Aucun droit d'administrateur requis.",
        "clipboard_monitor": "Collage auto. (Presse-papiers)"
    },
    "it": {
        "title": "Downloader Video e Audio YouTube",
        "title_twitter": "Downloader Video Twitter (X)",
        "title_facebook": "Downloader Video Facebook",
        "title_tiktok": "Downloader Video TikTok",
        "title_instagram": "Downloader Video e Reels Instagram",
        "title_soundcloud": "Downloader Audio SoundCloud",
        "title_reddit": "Downloader Video Reddit",
        "validate": "Convalidare",
        "download": "Scaricare",
        "language": "Selezione della lingua",
        "go_back": "Indietro",
        "url_label": "URL:",
        "folder_label": "Cartella di download:",
        "format_label": "Formato:",
        "format_label_audio": "Formato Audio:",
        "format_label_video": "Formato Video:",
        "list_type_video": "Video",
        "list_type_audio": "Audio",
        "quality_360p": "360p",
        "quality_480p": "480p",
        "quality_720p": "720p",
        "quality_1080p": "1080p",
        "quality_1440p": "1440p",
        "quality_2160p": "2160p (4K)",
        "quality_4320p": "4320p (8K)",
        "mp4": "MP4",
        "webm": "WEBM",
        "mkv": "MKV",
        "mp3": "MP3",
        "m4a": "M4A",
        "ogg": "OGG",
        "flac": "FLAC",
        "opus": "Opus",
        "wav": "WAV",
        "browse": "Esplora",
        "theme": "Cambia Tema",
        "download_type": "Tipo di Download:",
        "type_video": "Video Singolo",
        "type_playlist": "Playlist",
        "subtitle_download": "Scarica Sottotitoli",
        "subtitle_languages": "Lingue Sottotitoli (es: en,it):",
        "save_thumbnail": "Salva Miniatura",
        "ffmpeg_missing_title": "FFmpeg Mancante",
        "ffmpeg_missing_text": "FFmpeg non trovato per l'unione e la conversione audio/video.\n"
                             "Installa FFmpeg e aggiungilo al PATH di sistema.\n"
                             "L'applicazione potrebbe non riuscire during il download di audio o video di alta qualità.",
        "thumbnail_save_success_title": "Successo",
        "thumbnail_save_success_text": "Miniatura salvata in {path}",
        "youtube_invalid_url": "URL YouTube o YouTube Music non valido!",
        "twitter_invalid_url": "URL Twitter (X) non valido! Inserisci un link a un tweet.",
        "facebook_invalid_url": "URL Facebook non valido! Inserisci un link a un video o a un reel.",
        "tiktok_invalid_url": "URL TikTok non valido! Inserisci un link video.",
        "instagram_invalid_url": "URL Instagram non valido! Inserisci un link a un post o a un reel.",
        "soundcloud_invalid_url": "URL SoundCloud non valido! Inserisci un link a una traccia o playlist.",
        "reddit_invalid_url": "URL Reddit non valido! Inserisci un link a un post.",
        "download_in_progress": "📥 Download in corso: {percent}% completato",
        "download_complete": "✅ Download completato con successo!",
        "download_error": "❌ Si è verificato un errore during il download.",
        "download_starting": "⏳ Avvio del download... Attendere prego.",
        "download_speed_eta": "🚀 Velocità: {speed} | ⏳ Tempo rimanente: {eta}",
        "download_canceled": "⚠️ Download annullato.",
        "update_button": "Controlla aggiornamenti",
        "update_checking": "Controllo aggiornamenti...",
        "update_success": "yt-dlp è già aggiornato.",
        "update_available": "yt-dlp aggiornato con successo!",
        "update_error": "Si è verificato un errore during l'aggiornamento:\n{error}",
        
        # --- Ayar Metinleri ---
        "settings_title": "Impostazioni",
        "settings_tab_general": "Generale",
        "settings_tab_advanced": "Avanzate",
        "settings_cookie_label": "Percorso file cookie (.txt):",
        "settings_cookie_tooltip": "Seleziona un file cookies.txt (per video privati o con restrizioni di età).",
        "settings_save_button": "Salva",
        "settings_close_button": "Chiudi",
        "settings_button": "Impostazioni",
        "group_input": "Input",
        "group_options": "Opzioni di Download",
        "ffmpeg_warning_text": "FFmpeg non trovato. È richiesto per i download di audio e video di alta qualità.\n\nInstallalo utilizzando il pulsante 'Installazione automatica' in Impostazioni -> Avanzate.",
        "settings_group_cookie": "File Cookie",
        "settings_group_ffmpeg": "Installazione FFmpeg",
        "ffmpeg_status_found": "Stato: Trovato (AppData o PATH)",
        "ffmpeg_status_missing": "Stato: Non trovato",
        "ffmpeg_button_install": "Installazione automatica",
        "ffmpeg_button_reinstall": "Reinstalla / Aggiorna",
        "ffmpeg_tooltip_found": "FFmpeg è stato trovato sul tuo sistema (nella cartella AppData o nel PATH di sistema).",
        "ffmpeg_tooltip_missing": "Questo installerà FFmpeg nella cartella AppData e lo aggiungerà al tuo PATH. Non sono richiesti diritti di amministratore.",
        "clipboard_monitor": "Incolla auto. (Appunti)"
    },
    "pt": {
        "title": "Baixador de Vídeo e Áudio do YouTube",
        "title_twitter": "Baixador de Vídeo do Twitter (X)",
        "title_facebook": "Baixador de Vídeo do Facebook",
        "title_tiktok": "Baixador de Vídeo do TikTok",
        "title_instagram": "Baixador de Vídeo e Reels do Instagram",
        "title_soundcloud": "Baixador de Áudio do SoundCloud",
        "title_reddit": "Baixador de Vídeo do Reddit",
        "validate": "Validar",
        "download": "Baixar",
        "language": "Seleção de Idioma",
        "go_back": "Voltar",
        "url_label": "URL:",
        "folder_label": "Pasta de Download:",
        "format_label": "Formato:",
        "format_label_audio": "Formato de Áudio:",
        "format_label_video": "Formato de Vídeo:",
        "list_type_video": "Vídeo",
        "list_type_audio": "Áudio",
        "quality_360p": "360p",
        "quality_480p": "480p",
        "quality_720p": "720p",
        "quality_1080p": "1080p",
        "quality_1440p": "1440p",
        "quality_2160p": "2160p (4K)",
        "quality_4320p": "4320p (8K)",
        "mp4": "MP4",
        "webm": "WEBM",
        "mkv": "MKV",
        "mp3": "MP3",
        "m4a": "M4A",
        "ogg": "OGG",
        "flac": "FLAC",
        "opus": "Opus",
        "wav": "WAV",
        "browse": "Procurar",
        "theme": "Alterar Tema",
        "download_type": "Tipo de Download:",
        "type_video": "Vídeo Único",
        "type_playlist": "Playlist",
        "subtitle_download": "Baixar Legendas",
        "subtitle_languages": "Idiomas das Legendas (ex: en,pt):",
        "save_thumbnail": "Salvar Miniatura",
        "ffmpeg_missing_title": "FFmpeg Ausente",
        "ffmpeg_missing_text": "FFmpeg não encontrado para mesclagem e conversão de áudio/vídeo.\n"
                             "Instale o FFmpeg e adicione-o ao PATH do sistema.\n"
                             "O aplicativo pode falhar ao baixar áudio ou vídeo de alta qualidade.",
        "thumbnail_save_success_title": "Sucesso",
        "thumbnail_save_success_text": "Miniatura salva em {path}",
        "youtube_invalid_url": "URL do YouTube ou YouTube Music inválida!",
        "twitter_invalid_url": "URL do Twitter (X) inválida! Insira um link de tweet.",
        "facebook_invalid_url": "URL do Facebook inválida! Insira um link de vídeo ou reel.",
        "tiktok_invalid_url": "URL do TikTok inválida! Insira um link de vídeo.",
        "instagram_invalid_url": "URL do Instagram inválida! Insira um link de postagem ou reel.",
        "soundcloud_invalid_url": "URL do SoundCloud inválida! Insira um link de faixa ou playlist.",
        "reddit_invalid_url": "URL do Reddit inválida! Insira um link de postagem.",
        "download_in_progress": "📥 Baixando: {percent}% concluído",
        "download_complete": "✅ Download concluído com sucesso!",
        "download_error": "❌ Ocorreu um erro during o download.",
        "download_starting": "⏳ Iniciando o download... Por favor, aguarde.",
        "download_speed_eta": "🚀 Velocidade: {speed} | ⏳ Tempo restante: {eta}",
        "download_canceled": "⚠️ Download cancelado.",
        "update_button": "Verificar Atualizações",
        "update_checking": "Verificando atualizações...",
        "update_success": "yt-dlp já está atualizado.",
        "update_available": "yt-dlp atualizado com sucesso!",
        "update_error": "Ocorreu um erro during a atualização:\n{error}",
        
        # --- Ayar Metinleri ---
        "settings_title": "Configurações",
        "settings_tab_general": "Geral",
        "settings_tab_advanced": "Avançado",
        "settings_cookie_label": "Caminho do arquivo de cookies (.txt):",
        "settings_cookie_tooltip": "Selecione um arquivo cookies.txt (para vídeos privados ou com restrição de idade).",
        "settings_save_button": "Salvar",
        "settings_close_button": "Fechar",
        "settings_button": "Configurações",
        "group_input": "Entrada",
        "group_options": "Opções de Download",
        "ffmpeg_warning_text": "FFmpeg não encontrado. É necessário para downloads de áudio e vídeo de alta qualidade.\n\nInstale-o usando o botão 'Instalação automática' em Configurações -> Avançado.",
        "settings_group_cookie": "Arquivo de Cookies",
        "settings_group_ffmpeg": "Instalação do FFmpeg",
        "ffmpeg_status_found": "Status: Encontrado (AppData ou PATH)",
        "ffmpeg_status_missing": "Status: Não encontrado",
        "ffmpeg_button_install": "Instalação automática",
        "ffmpeg_button_reinstall": "Reinstalar / Atualizar",
        "ffmpeg_tooltip_found": "O FFmpeg foi encontrado no seu sistema (na pasta AppData ou PATH do sistema).",
        "ffmpeg_tooltip_missing": "Isso instalará o FFmpeg na pasta AppData e o adicionará ao PATH. Não são necessários direitos de administrador.",
        "clipboard_monitor": "Colar auto. (Área de transf.)"
    },
    "ru": {
        "title": "Загрузчик видео и аудио с YouTube",
        "title_twitter": "Загрузчик видео из Twitter (X)",
        "title_facebook": "Загрузчик видео с Facebook",
        "title_tiktok": "Загрузчик видео из TikTok",
        "title_instagram": "Загрузчик видео и Reels из Instagram",
        "title_soundcloud": "Загрузчик аудио с SoundCloud",
        "title_reddit": "Загрузчик видео с Reddit",
        "validate": "Проверить",
        "download": "Загрузить",
        "language": "Выбор языка",
        "go_back": "Назад",
        "url_label": "URL:",
        "folder_label": "Папка для загрузки:",
        "format_label": "Формат:",
        "format_label_audio": "Аудио Формат:",
        "format_label_video": "Видео Формат:",
        "list_type_video": "Видео",
        "list_type_audio": "Аудио",
        "quality_360p": "360p",
        "quality_480p": "480p",
        "quality_720p": "720p",
        "quality_1080p": "1080p",
        "quality_1440p": "1440p",
        "quality_2160p": "2160p (4K)",
        "quality_4320p": "4320p (8K)",
        "mp4": "MP4",
        "webm": "WEBM",
        "mkv": "MKV",
        "mp3": "MP3",
        "m4a": "M4A",
        "ogg": "OGG",
        "flac": "FLAC",
        "opus": "Opus",
        "wav": "WAV",
        "browse": "Просмотр",
        "theme": "Сменить тему",
        "download_type": "Тип загрузки:",
        "type_video": "Одно видео",
        "type_playlist": "Плейлист",
        "subtitle_download": "Скачать Субтитры",
        "subtitle_languages": "Языки Субтитров (напр: en,ru):",
        "save_thumbnail": "Сохранить Миниатюru",
        "ffmpeg_missing_title": "FFmpeg отсутствует",
        "ffmpeg_missing_text": "FFmpeg не найден для объединения и преобразования аудио/видео.\n"
                             "Установите FFmpeg и добавьте его в системный PATH.\n"
                             "Приложение может дать сбой при загрузке аудио или видео высокого качества.",
        "thumbnail_save_success_title": "Успех",
        "thumbnail_save_success_text": "Миниатюра сохранена в {path}",
        "youtube_invalid_url": "Неверный URL YouTube или YouTube Music!",
        "twitter_invalid_url": "Неверный URL Twitter (X)! Введите ссылку на твит.",
        "facebook_invalid_url": "Неверный URL Facebook! Введите ссылку на видео или reel.",
        "tiktok_invalid_url": "Неверный URL TikTok! Введите ссылку на видео.",
        "instagram_invalid_url": "Неверный URL Instagram! Введите ссылку на пост или reel.",
        "soundcloud_invalid_url": "Неверный URL SoundCloud! Введите ссылку на трек или плейлист.",
        "reddit_invalid_url": "Неверный URL Reddit! Введите ссылку на пост.",
        "download_in_progress": "📥 Загрузка: {percent}% завершено",
        "download_complete": "✅ Загрузка успешно завершена!",
        "download_error": "❌ Произошла ошибка при загрузке.",
        "download_starting": "⏳ Начинается загрузка... Пожалуйста, подождите.",
        "download_speed_eta": "🚀 Скорость: {speed} | ⏳ Оставшееся время: {eta}",
        "download_canceled": "⚠️ Загрузка отменена.",
        "update_button": "Проверить обновления",
        "update_checking": "Проверка обновлений...",
        "update_success": "yt-dlp уже обновлен.",
        "update_available": "yt-dlp успешно обновлен!",
        "update_error": "Произошла ошибка во время обновления:\n{error}",
        
        # --- Ayar Metinleri ---
        "settings_title": "Настройки",
        "settings_tab_general": "Общие",
        "settings_tab_advanced": "Дополнительно",
        "settings_cookie_label": "Путь к файлу Cookies (.txt):",
        "settings_cookie_tooltip": "Выберите файл cookies.txt (для частных видео или контента с возрастным ограничением).",
        "settings_save_button": "Сохранить",
        "settings_close_button": "Закрыть",
        "settings_button": "Настройки",
        "group_input": "Ввод",
        "group_options": "Параметры загрузки",
        "ffmpeg_warning_text": "FFmpeg не найден. Он необходим для загрузки аудио и видео высокого качества.\n\nПожалуйста, установите его с помощью кнопки 'Авто-установка' в Настройки -> Дополнительно.",
        "settings_group_cookie": "Файл Cookies",
        "settings_group_ffmpeg": "Установка FFmpeg",
        "ffmpeg_status_found": "Статус: Найден (AppData или PATH)",
        "ffmpeg_status_missing": "Статус: Не найден",
        "ffmpeg_button_install": "Авто-установка",
        "ffmpeg_button_reinstall": "Переустановить / Обновить",
        "ffmpeg_tooltip_found": "FFmpeg найден в вашей системе (в папке AppData или системном PATH).",
        "ffmpeg_tooltip_missing": "Это установит FFmpeg в папку AppData и добавит его в ваш PATH. Права администратора не требуются.",
        "clipboard_monitor": "Авто-вставка (Буфер)"
    },
    "ar": {
        "title": "مُحمل الفيديو والصوت من يوتيوب",
        "title_twitter": "محمل الفيديو من تويتر (X)",
        "title_facebook": "محمل الفيديو من فيسبوك",
        "title_tiktok": "محمل الفيديو من تيك توك",
        "title_instagram": "محمل الفيديو والريلز من انستجرام",
        "title_soundcloud": "محمل الصوت من ساوند كلاود",
        "title_reddit": "محمل الفيديو من ريديت",
        "validate": "تحقق",
        "download": "تنزيل",
        "language": "اختيار اللغة",
        "go_back": "رجوع",
        "url_label": "URL:",
        "folder_label": "مجلد التنزيل:",
        "format_label": "التنسيق:",
        "format_label_audio": "تنسيق الصوت:",
        "format_label_video": "تنسيق الفيديو:",
        "list_type_video": "فيديو",
        "list_type_audio": "صوت",
        "quality_360p": "360p",
        "quality_480p": "480p",
        "quality_720p": "720p",
        "quality_1080p": "1080p",
        "quality_1440p": "1440p",
        "quality_2160p": "2160p (4K)",
        "quality_4320p": "4320p (8K)",
        "mp4": "MP4",
        "webm": "WEBM",
        "mkv": "MKV",
        "mp3": "MP3",
        "m4a": "M4A",
        "ogg": "OGG",
        "flac": "FLAC",
        "opus": "Opus",
        "wav": "WAV",
        "browse": "استعرض",
        "theme": "تغيير الموضوع",
        "download_type": "نوع التنزيل:",
        "type_video": "مقطع فيديو واحد",
        "type_playlist": "قائمة تشغيل",
        "subtitle_download": "تنزيل الترجمات",
        "subtitle_languages": "لغات الترجمة (مثل: en,ar):",
        "save_thumbnail": "حفظ الصورة المصغرة",
        "ffmpeg_missing_title": "FFmpeg مفقود",
        "ffmpeg_missing_text": "لم يتم العثور على FFmpeg لدمج وتحويل الصوت/الفيديو.\n"
                             "يرجى تثبيت FFmpeg وإضافته إلى مسار النظام الخاص بك.\n"
                             "قد يفشل التطبيق عند تنزيل الصوت أو الفيديو عالي الجودة.",
        "thumbnail_save_success_title": "نجاح",
        "thumbnail_save_success_text": "تم حفظ الصورة المصغرة في {path}",
        "youtube_invalid_url": "رابط YouTube أو YouTube Music غير صالح!",
        "twitter_invalid_url": "رابط Twitter (X) غير صالح! يرجى إدخال رابط تغريدة.",
        "facebook_invalid_url": "رابط Facebook غير صالح! يرجى إدخال رابط فيديو أو ريل.",
        "tiktok_invalid_url": "رابط TikTok غير صالح! يرجى إدخال رابط فيديو.",
        "instagram_invalid_url": "رابط Instagram غير صالح! يرجى إدخال رابط منشور أو ريل.",
        "soundcloud_invalid_url": "رابط SoundCloud غير صالح! يرجى إدخال رابط مقطع صوتي أو قائمة تشغيل.",
        "reddit_invalid_url": "رابط Reddit غير صالح! يرجى إدخال رابط منشور.",
        "download_in_progress": "📥 جاري التنزيل: {percent}% مكتمل",
        "download_complete": "✅ اكتمل التنزيل بنجاح!",
        "download_error": "❌ حدث خطأ أثناء التنزيل.",
        "download_starting": "⏳ بدء التنزيل... يرجى الانتظار.",
        "download_speed_eta": "🚀 السرعة: {speed} | ⏳ الوقت المتبقي: {eta}",
        "download_canceled": "⚠️ تم إلغاء التنزيل.",
        "update_button": "التحقق من التحديثات",
        "update_checking": "جاري التحقق من التحديثات...",
        "update_success": "yt-dlp محدث بالفعل.",
        "update_available": "تم تحديث yt-dlp بنجاح!",
        "update_error": "حدث خطأ أثناء التحديث:\n{error}",
        
        # --- Ayar Metinleri ---
        "settings_title": "الإعدادات",
        "settings_tab_general": "عام",
        "settings_tab_advanced": "متقدم",
        "settings_cookie_label": "مسار ملف تعريف الارتباط (.txt):",
        "settings_cookie_tooltip": "حدد ملف cookies.txt (لمقاطع الفيديو الخاصة أو المقيدة بالعمر).",
        "settings_save_button": "حفظ",
        "settings_close_button": "إغلاق",
        "settings_button": "الإعدادات",
        "group_input": "إدخال",
        "group_options": "خيارات التنزيل",
        "ffmpeg_warning_text": "لم يتم العثور على FFmpeg. هذا مطلوب لتنزيلات الصوت والفيديو عالية الجودة.\n\nيرجى تثبيته باستخدام زر 'تثبيت تلقائي' في الإعدادات -> متقدم.",
        "settings_group_cookie": "ملف تعريف الارتباط",
        "settings_group_ffmpeg": "تثبيت FFmpeg",
        "ffmpeg_status_found": "الحالة: موجود (AppData أو PATH)",
        "ffmpeg_status_missing": "الحالة: غير موجود",
        "ffmpeg_button_install": "تثبيت تلقائي",
        "ffmpeg_button_reinstall": "إعادة تثبيت / تحديث",
        "ffmpeg_tooltip_found": "تم العثور على FFmpeg على نظامك (في مجلد AppData أو مسار النظام).",
        "ffmpeg_tooltip_missing": "سيؤدي هذا إلى تثبيت FFmpeg في مجلد AppData الخاص بك وإضافته إلى مسار النظام. لا يلزم وجود حقوق مسؤول.",
        "clipboard_monitor": "لصق تلقائي (الحافظة)"
    },
    "zh": {
        "title": "YouTube视频和音频下载器",
        "title_twitter": "Twitter (X) 视频下载器",
        "title_facebook": "Facebook 视频下载器",
        "title_tiktok": "TikTok 视频下载器",
        "title_instagram": "Instagram 视频和Reels下载器",
        "title_soundcloud": "SoundCloud 音频下载器",
        "title_reddit": "Reddit 视频下载器",
        "validate": "验证",
        "download": "下载",
        "language": "语言选择",
        "go_back": "返回",
        "url_label": "URL:",
        "folder_label": "下载文件夹:",
        "format_label": "格式:",
        "format_label_audio": "音频格式:",
        "format_label_video": "视频格式:",
        "list_type_video": "视频",
        "list_type_audio": "音频",
        "quality_360p": "360p",
        "quality_480p": "480p",
        "quality_720p": "720p",
        "quality_1080p": "1080p",
        "quality_1440p": "1440p",
        "quality_2160p": "2160p (4K)",
        "quality_4320p": "4320p (8K)",
        "mp4": "MP4",
        "webm": "WEBM",
        "mkv": "MKV",
        "mp3": "MP3",
        "m4a": "M4A",
        "ogg": "OGG",
        "flac": "FLAC",
        "opus": "Opus",
        "wav": "WAV",
        "browse": "浏览",
        "theme": "更改主题",
        "download_type": "下载类型:",
        "type_video": "单个视频",
        "type_playlist": "播放列表",
        "subtitle_download": "下载字幕",
        "subtitle_languages": "字幕语言 (例如: en,zh):",
        "save_thumbnail": "保存缩略图",
        "ffmpeg_missing_title": "缺少 FFmpeg",
        "ffmpeg_missing_text": "未找到用于音频/视频合并和转换的 FFmpeg。\n"
                             "请安装 FFmpeg 并将其添加到系统 PATH。\n"
                             "下载音频或高质量视频时, 应用程序可能会失败。",
        "thumbnail_save_success_title": "成功",
        "thumbnail_save_success_text": "缩略图已保存到 {path}",
        "youtube_invalid_url": "无效的 YouTube 或 YouTube Music URL！",
        "twitter_invalid_url": "无效的 Twitter (X) URL！请输入推文链接。",
        "facebook_invalid_url": "无效的 Facebook URL！请输入视频或Reel链接。",
        "tiktok_invalid_url": "无效的 TikTok URL！请输入视频链接。",
        "instagram_invalid_url": "无效的 Instagram URL！请输入帖子或Reel链接。",
        "soundcloud_invalid_url": "无效的 SoundCloud URL！请输入曲目或播放列表链接。",
        "reddit_invalid_url": "无效的 Reddit URL！请输入帖子链接。",
        "download_in_progress": "📥 下载中: {percent}% 已完成",
        "download_complete": "✅ 下载成功完成！",
        "download_error": "❌ 下载过程中出现错误。",
        "download_starting": "⏳ 下载开始... 请稍候。",
        "download_speed_eta": "🚀 Vitesse: {speed} | ⏳ 剩余时间: {eta}",
        "download_canceled": "⚠️ 下载已取消。",
        "update_button": "检查更新",
        "update_checking": "正在检查更新...",
        "update_success": "yt-dlp 已是最新版本。","update_available": "yt-dlp 更新成功！",
        "update_error": "更新过程中出错：\n{error}",
        
        # --- Ayar Metinleri ---
        "settings_title": "设置",
        "settings_tab_general": "常规",
        "settings_tab_advanced": "高级",
        "settings_cookie_label": "Cookies 文件路径 (.txt):",
        "settings_cookie_tooltip": "选择一个 cookies.txt 文件 (用于私人视频或有年龄限制的内容).",
        "settings_save_button": "保存",
        "settings_close_button": "关闭",
        "settings_button": "设置",
        "group_input": "输入",
        "group_options": "下载选项",
        "ffmpeg_warning_text": "未找到 FFmpeg。下载音频和高质量视频需要它。\n\n请在 设置 -> 高级 中使用 '自动安装' 按钮进行安装。",
        "settings_group_cookie": "Cookie 文件",
        "settings_group_ffmpeg": "FFmpeg 安装",
        "ffmpeg_status_found": "状态: 已找到 (AppData 或 PATH)",
        "ffmpeg_status_missing": "状态: 未找到",
        "ffmpeg_button_install": "自动安装",
        "ffmpeg_button_reinstall": "重新安装 / 更新",
        "ffmpeg_tooltip_found": "在您的系统上找到了 FFmpeg (在您的 AppData 文件夹或系统 PATH 中).",
        "ffmpeg_tooltip_missing": "这将安装 FFmpeg 到您的 AppData 文件夹并将其添加到您的 PATH。无需管理员权限。",
        "clipboard_monitor": "自动粘贴 (剪贴板)"
    }
}